version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - nodeapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
  nodeapp: 
    build: .
    image: mascarenesc/express-app:latest
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    restart: always

volumes:
  mongo-db:
